# Generated by Django 4.0.3 on 2022-03-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('m2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=23)),
                ('last_name', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_name', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=50)),
                ('no_of_apartments', models.IntegerField()),
                ('www', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.apartment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.customer')),
                ('invest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.invest')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.offer')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='invest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.invest'),
        ),
    ]
