# Generated by Django 4.0.3 on 2022-03-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRM.apartment'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRM.customer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='invest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRM.invest'),
        ),
    ]
