# Generated by Django 4.0.3 on 2022-03-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
